name:   06 - Contexts

run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }} # This will show the workflow name in the run name

on:
    push:
    workflow_dispatch:
     inputs:
        debug:
         type: boolean
         default: false
env:
    MY_WORKFLOW_VAR: "workflow" 
    MY_OVERWRITTEN_VAR: "workflow"

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            JOB: "job"
        steps:
            - name: Display Information
              run: |
                echo "Repository: ${{ github.repository }}"
                echo "Event Name: ${{ github.event_name }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Job: ${{ github.job }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"
                echo "SHA: ${{ github.sha }}"
                echo "Ref: ${{ github.ref }}"
            - name: Retrieve Variables
              run: |
                echo "Variable value: ${{ vars.MY_VAR }}"
            - name: Print Environment Variables
              env:
                MY_OVERWRITTEN_VAR: "step"
              run: |
                echo "Workflow env: ${{env.MY_WORKFLOW_VAR}}"
                echo "Overwritten env: ${{env.MY_OVERWRITTEN_VAR}}"
                
                